# action.yml
name: 'Dependabot Action - Kenna'
description: 'Dependabot Action to push results into Kenna'
author: GeekMasher

inputs:
  endpoint:
    description: 'Kenna Endpoint'   
    required: true
  kenna_token:
    description: 'Kenna Access Token'
    required: true
  connector:
    description: 'Kenna Connector ID'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -e ${{ inputs.endpoint }}
    - -k ${{ inputs.kenna_token }}
    - -c ${{ inputs.connector }}
